FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN python -m venv venv

ENV PATH="/app/venv/bin:$PATH"

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "prediction:app", "--host", "0.0.0.0", "--port", "8000"]